name: ✨ Feature Request
description: Suggest a feature to add in a future Scaffold version.
labels:
  - enhancement
body:
  - type: textarea
    id: feature-description
    attributes:
      label: Describe the feature you'd like
      description: >-
        A clear description of the feature you feel should be implemented.
    validations:
      required: true
  - type: textarea
    id: feature-usefulness
    attributes:
      label: Usefulness/application of the feature
      description: >-
        Include possible scenarios or situations where this feature would be useful.
  - type: textarea
    id: additional-context
    attributes:
      label: Additional context (include screenshots or videos, if applicable)
      description: >-
        You may use image hosting services, such as [Imgur](https://imgur.com/), for screenshots. You
        can also use [YouTube](https://www.youtube.com/) or [Streamable](https://streamable.com/) for video hosting.